// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA916VO3Hv-iBs7hLWbZB9DKkVHTBQvTI0',
    appId: '1:344264346912:web:538fd24f94b450a48f9b45',
    messagingSenderId: '344264346912',
    projectId: 'etoet-pe2022',
    authDomain: 'etoet-pe2022.firebaseapp.com',
    storageBucket: 'etoet-pe2022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC38jxvHWLKSPWP6iXKtmjLcrnHuWqjvmA',
    appId: '1:344264346912:android:04211c74b10c46618f9b45',
    messagingSenderId: '344264346912',
    projectId: 'etoet-pe2022',
    storageBucket: 'etoet-pe2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzm0LqFvcDLqsUTa1YOZwM2BkotoOO1kQ',
    appId: '1:344264346912:ios:12583481ea92e4508f9b45',
    messagingSenderId: '344264346912',
    projectId: 'etoet-pe2022',
    storageBucket: 'etoet-pe2022.appspot.com',
    iosClientId: '344264346912-6sfjhcgr9842sd14a8ov1nu8rs88f4li.apps.googleusercontent.com',
    iosBundleId: 'com.deltadeer.etoet',
  );
}
